# cd ~/work/git/public_repos/repo-template; docker buildx build --platform=linux/amd64 -t repo-template:nbsphinx -f Deploy/Dockerfile-make-docs .
FROM sphinxdoc/sphinx

# Install deps
RUN apt-get update
RUN apt-get install -y --no-install-recommends pandoc
RUN apt-get update --allow-releaseinfo-change -y && apt-get install -y pandoc librsvg2-bin inkscape latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended fonts-lmodern

RUN pip3 install --upgrade pip

# RUN pip intall sphinx # FAILS...?
RUN pip install nbsphinx \
    nbsphinx>=0.9.2 \
    sphinxcontrib.mermaid>==0.9.2 \
    sphinx-autoapi>=2.1.1 \
    sphinx-copybutton>=0.5.0 \
    myst-parser>=2.0.0 \
    furo>=2023.7.26 \
    jupyter-black>=0.3.4 \
    sphinxcontrib.bibtex>=2.6.2

# These are not really used...
RUN pip install sphinx_rtd_theme sphinx-gallery
# RUN pip install sphinxcontrib.rsvgconverter

RUN mkdir -p /repo-template
ENV HOME /repo-template
# WORKDIR /repo-template
COPY . /repo-template

WORKDIR /repo-template/docs
RUN make html

CMD ["/bin/bash"]
