# Copyright (c) 2025 takotime808

name: Documentation

on:
  push:
    branches: [main, master, surrogate_vendor]

permissions:
  contents: write

jobs:
  build-docs:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install project and doc dependencies
      run: |
        pip install --upgrade pip
        pip install .[test]  # if test dependencies help with doc build
        pip install sphinx
        pip install sphinx_rtd_theme
        pip install sphinx-click
        pip install nbsphinx>=0.9.2
        pip install sphinxcontrib-mermaid>=0.9.2
        pip install sphinx-autoapi>=2.1.1
        pip install sphinx-copybutton>=0.5.0
        pip install myst-parser>=2.0.0
        pip install furo>=2023.7.26
        pip install jupyter-black>=0.3.4
        pip install sphinxcontrib-bibtex>=2.6.2
        pip install sphinx-gallery

    - name: Build Sphinx HTML
      # run: |
      #   cd docs
      #   make html
      working-directory: docs
      run: make html

    # - name: Build HTML
    #   working-directory: docs
    #   run: sphinx-build -b html . _build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        force_orphan: true
        full_commit_message: ${{ github.event.head_commit.message }}
